// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_boLEacKvrubW5edVuMh-B4zRuXKNfBg',
    appId: '1:323212705120:web:10c9a30e21a0dc29d83205',
    messagingSenderId: '323212705120',
    projectId: 'library001-a53a4',
    authDomain: 'library001-a53a4.firebaseapp.com',
    storageBucket: 'library001-a53a4.firebasestorage.app',
    measurementId: 'G-1BSSHN3E9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVyucFRtvp6hZwPCo0dDAQRsfPBZ_2GbE',
    appId: '1:323212705120:android:a789a72ac8b84fd4d83205',
    messagingSenderId: '323212705120',
    projectId: 'library001-a53a4',
    storageBucket: 'library001-a53a4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmQFgKF6cRQsBf4489ra4nSgSV6Z-tUHM',
    appId: '1:323212705120:web:3ce0af3b5be798c2d83205',
    messagingSenderId: '323212705120',
    projectId: 'library001-a53a4',
    authDomain: 'library001-a53a4.firebaseapp.com',
    storageBucket: 'library001-a53a4.firebasestorage.app',
    measurementId: 'G-WVRL5L0E5V',
  );
}
